### ISSUE TITLE
Test failure in `cargo test --features java`

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-old#9]
running `cargo test --features java` gives the following failure.
```
running 5 tests
[2020-07-10T13:26:31Z INFO  bdk::api::test] TEST init_update_remove_config()
test config::test::save_load_delete ... ok
test config::test::save_update_load_delete ... ok
test wallet::test::process_blocks_balance ... ok
test api::test::init_start_stop_remove_config ... FAILED
test api::test::init_update_remove_config ... ok

failures:

---- api::test::init_start_stop_remove_config stdout ----
thread 'api::test::init_start_stop_remove_config' panicked at 'Builder::init should not be called after logger initialized: SetLoggerError(())', /home/raj/.cargo/registry/src/github.com-1ecc6299db9ec823/env_logger-0.7.1/src/lib.rs:703:9

```
Failure backtrace
```
14: core::option::expect_none_failed
             at src/libcore/option.rs:1268
15: core::result::Result<T,E>::expect
             at /home/raj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:963
16: env_logger::Builder::init
             at /home/raj/.cargo/registry/src/github.com-1ecc6299db9ec823/env_logger-0.7.1/src/lib.rs:703
17: bdk::api::test::init_start_stop_remove_config
             at src/api.rs:350
18: bdk::api::test::init_start_stop_remove_config::{{closure}}
             at src/api.rs:349
19: core::ops::function::FnOnce::call_once
             at /home/raj/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
```
Curiously, the test passes as a stand-alone.
```
$ cargo test init_start_stop_remove_config --features java

running 1 test
[2020-07-10T13:30:28Z INFO  bdk::api::test] TEST init_start_stop_remove_config()
[2020-07-10T13:30:29Z INFO  bdk::api::test] start 1
[2020-07-10T13:30:29Z INFO  bdk::api::test] start 2
[2020-07-10T13:30:29Z INFO  bdk::api] config file path: ./regtest/bdk.cfg
[2020-07-10T13:30:29Z INFO  murmel::chaindb] no header tip found
[2020-07-10T13:30:29Z INFO  murmel::chaindb] initialized with genesis header 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
[2020-07-10T13:30:30Z INFO  bdk::api] Wallet balance: 0 satoshis 0 available
[2020-07-10T13:30:30Z INFO  bdk::api] start check_stopped
[2020-07-10T13:30:30Z INFO  bdk::api] stopping
[2020-07-10T13:30:30Z INFO  bdk::api::test] stop returned
[2020-07-10T13:30:30Z INFO  bdk::api::test] removed config
test api::test::init_start_stop_remove_config ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out
```

**Comment by notmandatory** [comment]
@rajarshimaitra this should be fixed now in master branch. Give it a try and if it looks good we can close this one.

**Comment by rajarshimaitra** [comment]
Fix ACK.
